### ISSUE TITLE
Make routes for Adding likes and comments

### ISSUE THREAD

**Issue by MananDesai54** [dkp1903/devagram-backend#23]

**Comment by ayushpaharia** [comment]
Im working on thisissue

**Comment by MananDesai54** [comment]
Okay cool, but remember that comments can also have likes, and user can only reply to root comment , user cannot reply on Sun comments like Instagram

**Comment by MananDesai54** [comment]
First make basic like and comments for posts only @ayushpaharia

**Comment by MananDesai54** [comment]
@ayushpaharia are you working on that ?

**Comment by ayushpaharia** [comment]
Yes I am. I'll keep you updated

**Comment by MananDesai54** [comment]
you are testing it with Postman ? @ayushpaharia

**Comment by ayushpaharia** [comment]
Completed

**Comment by MananDesai54** [comment]
completed
