### ISSUE TITLE
Making routes for  Hackathons

### ISSUE THREAD

**Issue by MananDesai54** [dkp1903/devagram-backend#25]
- User can **participate** in hackathon
- User can **view and edit some details** like name, email after participating
- User can see **Details of all the hackathons**
- User can **see all the participants** of the hackathon in which he/she participated.
- Users can **un-register** themselves whenever they want.

**Comment by developer-AAKASH** [comment]
I would like to work on this !!!

**Comment by MananDesai54** [comment]
Go for it

**Comment by MananDesai54** [comment]
Done
